### ISSUE TITLE
Compatibility issue with newer versions of libtorch

### ISSUE THREAD

**Issue by JinTonic101** [vvmnnnkv/libtorchjs#2]
Hi there,

As discussed before, there are some compatibility issue when loading a newer version of pytorch model, so it could be great if you recompile the module binaries with the latest version of libtorch.

Thank you in advance!

**Comment by vvmnnnkv** [comment]
Hi @JinTonic101 
Thank you for reporting the problem!
I've updated code to compile linux version of libtorchjs with libtorch v1.4.0.
Please check libtorchjs `1.0.0-alpha.4`? It works fine with [nodejs-style-transfer](https://github.com/vvmnnnkv/nodejs-style-transfer) example.

**Comment by JinTonic101** [comment]
Hi @vvmnnnkv 
Working fine now ! I've managed to load my model, but I've got another issue regarding the invalid input Tensor type (I'll create a new issue), thanks !
