### ISSUE TITLE
Error while downloading in npm window

### ISSUE THREAD

**Issue by Jungofalltrades** [vvmnnnkv/libtorchjs#5]
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://libtorchjs.s3.amazonaws.com/libtorchjs/v1.0.0-alpha.4/Release/win32-x64-napi-v3.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (C:\Users\troop\server\node_modules\node-pre-gyp\lib\install.js:142:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:323:22)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\troop\server\node_modules\needle\lib\needle.js:488:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:418:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:311:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:476:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:311:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\troop\\server\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\troop\server\node_modules\libtorchjs
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://libtorchjs.s3.amazonaws.com/libtorchjs/v1.0.0-alpha.4/Release/win32-x64-napi-v3.tar.gz
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libtorchjs@1.0.0-alpha.4 install: `node-pre-gyp install --fallback-to-build=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libtorchjs@1.0.0-alpha.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

------------------------------------------------------------------------------------------------------
how can I solve and download libtorchjs??

**Comment by vvmnnnkv** [comment]
@seiglin should be fixed now

**Comment by vvmnnnkv** [comment]
Closing
